### PR TITLE
Modified name for common types macro scope.

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

# Pull request

**Choose Correct**

- [ ] bug
- [X] feature

**Describe the pull request**

Description https://github.com/EmbeddedRPC/erpc/issues/336
Default change from ERPC_TYPE_DEFINITIONS to ERPC_TYPE_DEFINITIONS_erpcShim
Default with program name change from ERPC_TYPE_DEFINITIONS to ERPC_TYPE_DEFINITIONS_<programName>
Using annotation value for ` @scope_name`  change from ERPC_TYPE_DEFINITIONS to ERPC_TYPE_DEFINITIONS_<annotationValue>

**To Reproduce**

See tests

**Expected behavior**

See tests

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [x] PR code is tested.
- [X] PR code is formatted.
- [X] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Diagano** [comment]
Not that its mattrers much but maytbe convert to uppercase in the template use of the scope_name?
{$upper(scope_name)}

**Comment by Hadatko** [comment]
Yeah i was thinking about that and i wanted to let it on user. User can use upper case in his definition. 
@MichalPrincNXP what do you think?

**Comment by Diagano** [comment]
Well two points about that:
1. User choice in that case will also impact file naming
2. Use of lower case as default also counters that in some sense.

**Comment by Hadatko** [comment]
Well make sense. But i need distuinguish between annotation value and program name and use upper case only when annotation was not used.

**Comment by Diagano** [comment]
Got it. As I mentioned, I lack the system wide view and impacts. Thank you!

**Comment by Hadatko** [comment]
@Diagano i decided to do it as you proposed. UpperCase. It is because the macro name is still with eRPC prefix and users shouldn't use it and be aware of its existention. Will see future requests :D

**Comment by Hadatko** [comment]
@MichalPrincNXP what do you think about this PR?

**Comment by MichalPrincNXP** [comment]
> @MichalPrincNXP what do you think about this PR?

I agree with the approach. There are some build fails after the rebase however:

erpcgen/src/Generator.cpp:98:14: error: 'transform' is not a member of 'std'
    std::transform(scopeNameC.begin(), scopeNameC.end(), scopeNameC.begin(), ::toupper);

Probably, the #include <algorithm> will be needed.
